### ISSUE TITLE
Use moveit only to calculate trajectories

### ISSUE THREAD

**Issue by RodrigoCodeBernardo** [ros-planning/moveit_tutorials#597] opened 2021-03-10 14:01 UTC
### Your environment
* ROS Distro: melodic

Is it possible to use moveit only to calculate trajectories? I am creating a toolbox to control a UR3 and want to use moveit only for calculating trajectories. 

So far I have been using the command to use moveit:

roslaunch ur3_moveit_config ur3_moveit_planning_execution.launch limited:=true

his method works, but it ties a lot of nos that I don't need to use. How can I do this and which nodes does moveit use in the trajectory calculation?

Thanks for help

**Comment by felixvd** [comment] 2021-03-10 14:27
This is more suited for a ROS answers question, but how will you execute the trajectories? Unless you use only the Pilz industrial motion planner, there will be no equivalent in URScript to execute what you calculate. If your toolbox ends up just recreating MoveIt, you won't have gained much.

Apart from that I am unsure what exactly you are asking, but you can gain more insight into the pipeline by looking at the `MoveGroupInterface`'s `plan` and `execute` functions.

**Comment by RodrigoCodeBernardo** [comment] 2021-03-10 14:57
My goal is to not have the ur3 console so I can work with my arm.

I already have an action server that accepts the moveit message, and executes the trajectory.  My action gets the parameters (positions, velocities and accelerations)

            for i in range(n_points):
                        
                positions.append(plan.joint_trajectory.points[i].positions)
                velocities.append(plan.joint_trajectory.points[i].velocities)
                accelerations.append(plan.joint_trajectory.points[i].accelerations)   

I just wanted to release the NOS that moveit uses to calculate the plan

**Comment by felixvd** [comment] 2021-03-10 15:04
I guess by "moveit message" you mean the JointTrajectory message, but I don't understand what you mean by "NOS" or "ur3 console".

Are you sure that you're not reimplementing something unnecessarily? Normally one would use the [official driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver) to control the robot. Their controllers already advertise actions that accepts JointTrajectory messages.

**Comment by RodrigoCodeBernardo** [comment] 2021-03-10 15:17
console = teach pendant; NOS = ROS NODES

Yes but you would have to have Urcap running to work, if I understood correctly on the universal robotics website.

So I wanted my moveit launch to launch only what was necessary for trajectory planning.

**Comment by felixvd** [comment] 2021-03-11 15:05
To be honest I don't really see the point, as both MoveIt and the UR seem to work as intended. But you can try going through the launch file you mentioned in your first post and remove sections, and see if the trajectory planning as you envision it still works. Maybe you will learn something about the code and in what ways the problem isn't simple.

**Comment by felixvd** [comment] 2021-04-05 15:07
Closing because this seems to be solved

**Closed by felixvd** 2021-04-05 15:07 UTC
