### ISSUE TITLE
fake controllers under indigo

### ISSUE THREAD

**Issue by danielhoeltgen** [ros-planning/moveit_tutorials#46] opened 2016-11-02 10:22 UTC
The fake controllers only jump to the last state and do not interpolate as described in [this tutorial](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/fake_controller_manager_tutorial.html).
The problem seems to be fixed under kinetic as discussed [here](https://groups.google.com/forum/#!topic/moveit-users/S-Cve5DFMS4)

**Comment by rhaschke** [comment] 2016-11-02 10:51
The corresponding changes were merged into Indigo with https://github.com/ros-planning/moveit/commit/21fd7e2e6414a8bcb39091ba1cc8fcfdfd2169e4.
However, there wasn't a release since then. Did you build from source?

**Comment by danielhoeltgen** [comment] 2016-11-03 13:02
Great, I build it from source and now it works. There is still one problem: "rate" or "fake_interpolating_controlller_rate" do not seem to have any effect. The trajectory of the interpolate type is not smooth even for high rate values. Should this work or is it not implemented so far?

**Comment by rhaschke** [comment] 2017-01-10 23:08
The fake controllers publish their joint state via `/move_group/fake_controller_joint_states` that are republished by a `joint_state_publisher` to `/joint_states` and finally received by MoveIt and other tools again.
Along that pipeline, there are several point of throttling, which effectively limits the maximal rate.

**Comment by v4hn** [comment] 2017-01-12 12:55
Closing this. The controllers are available in indigo and the rate is limited by design limitations.

**Closed by v4hn** 2017-01-12 12:55 UTC
