### ISSUE TITLE
Segmentation fault (core dumped) when creating cpp file with IKFast

### ISSUE THREAD

**Issue by mohdwaseem27** [ros-planning/moveit_tutorials#514] opened 2020-08-13 13:01 UTC
### Description

I'm following this [tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast/ikfast_tutorial.html) to generate IK solver, but when I run `python openrave-config --python-dir/openravepy/_openravepy_/ikfast.py --robot="$MYROBOT_NAME".dae --iktype=transform6d --baselink="$BASE_LINK" --eelink="$EEF_LINK" --savefile="$IKFAST_OUTPUT_PATH"` 
I got ```

```
***equations***
WARNING: cannot evalute: [2.82550002602114*new_r20 - 2.71409750345368, -1.57114625518052, 2.82550002602114*new_r20 + 2.71409750345368]
WARNING: cannot evalute: [2.82550002602114*new_r21 - 0.785573127590261, 5.42819500690736, 2.82550002602114*new_r21 + 0.785573127590261]
WARNING: cannot evalute: [2.26040002081691*new_r00 + 1.69530001561268*new_r10 - 0.785573127590261, 5.42819500690736, 2.26040002081691*new_r00 + 1.69530001561268*new_r10 + 0.785573127590261]
WARNING: cannot evalute: [2.26040002081691*new_r01 + 1.69530001561268*new_r11 + 2.71409750345368, 1.57114625518052, 2.26040002081691*new_r01 + 1.69530001561268*new_r11 - 2.71409750345368]
WARNING: cannot evalute: [2.82550002602114*new_r00 - 0.628458502072209, 4.34255600552589, 2.82550002602114*new_r00 + 0.628458502072209]
WARNING: cannot evalute: [2.82550002602114*new_r01 + 2.17127800276295, 1.25691700414442, 2.82550002602114*new_r01 - 2.17127800276295]
WARNING: cannot evalute: [2.82550002602114*new_r10 - 0.471343876554157, 3.25691700414442, 2.82550002602114*new_r10 + 0.471343876554157]
WARNING: cannot evalute: [2.82550002602114*new_r11 + 1.62845850207221, 0.942687753108313, 2.82550002602114*new_r11 - 1.62845850207221]
WARNING: cannot evalute: [-3.57995499585488*new_r00 - 2.68496624689116*new_r10 - 4.29992499309147*new_r20 + 5.37455710576647, -6.20600109002855, -3.57995499585488*new_r00 - 2.68496624689116*new_r10 - 4.29992499309147*new_r20 - 5.37455710576647]
WARNING: cannot evalute: [-3.57995499585488*new_r01 - 2.68496624689116*new_r11 - 4.29992499309147*new_r21 - 3.10300054501427, -10.7491142115330, -3.57995499585488*new_r01 - 2.68496624689116*new_r11 - 4.29992499309147*new_r21 + 3.10300054501427]
WARNING: cannot evalute: [3.43993999447318*new_r00 + 2.57995499585488*new_r10 - 4.4749437448186*new_r20 + 3.10300054501427, 10.7491142115330, 3.43993999447318*new_r00 + 2.57995499585488*new_r10 - 4.4749437448186*new_r20 - 3.10300054501427]
WARNING: cannot evalute: [3.43993999447318*new_r01 + 2.57995499585488*new_r11 - 4.4749437448186*new_r21 + 5.37455710576647, -6.20600109002855, 3.43993999447318*new_r01 + 2.57995499585488*new_r11 - 4.4749437448186*new_r21 - 5.37455710576647]
INFO: generating cpp code...
INFO: c=1 var=j0
INFO: c=2 var=j4
INFO: c=3 var=j5
INFO: c=4 var=j3
INFO: c=5 var=j2
INFO: c=6, store solution
INFO: c=7, store solution
INFO: c=8, store solution
INFO: c=9 var=j0
INFO: c=10 var=j4
INFO: c=11 var=j5
INFO: c=12 var=j0
INFO: c=13 var=j4
INFO: c=14 var=j5
INFO: c=15 var=j0
INFO: c=16 var=j4
INFO: c=17 var=j5
INFO: c=18 var=j0
INFO: c=19 var=j4
INFO: c=20 var=j5
INFO: c=21 var=j0
INFO: c=22 var=j4
INFO: c=23 var=j5
INFO: c=24 var=j0
INFO: c=25 var=j4
INFO: c=26 var=j5
INFO: c=27 var=j0
INFO: c=28 var=j4
INFO: c=29 var=j5
INFO: c=30 var=j0
INFO: c=31 var=j4
INFO: c=32 var=j5
Segmentation fault (core dumped)

```
if someone could help me through this it would be great full
```

### Your environment
* ROS Distro: melodc
* OS Version: e.g. Ubuntu 18.04

**Comment by rhaschke** [comment] 2020-08-13 15:40
Looks like a duplicate of #417. Your following the quite old Kinetic tutorial. We have come up with a new, greatly simplified version: https://ros-planning.github.io/moveit_tutorials/doc/ikfast/ikfast_tutorial.html, which should also work on Kinetic in principle.
Maybe give it a try as well?

**Closed by rhaschke** 2020-08-13 15:40 UTC
